[package]
name = "dds-convert-util"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
image_dds = "0.6.2"
colored = "2.0"
tokio = { version = "1.29", features = ["full"] }
toml = "0.7"
serde = { version = "1.0", features = ["derive"] }