# Input directory path containing images to be processed
path_in = "./sample/samples_in"

# Output directory path where processed images will be saved
path_out = "./sample/samples_out"

# Maximum directory traversal depth
max_depth = 3

# List of target widths for resizing images
target_sizes = [512, 1024, 2048]

# Number of threads to use for concurrent processing
threads = 4
