# Input directory path containing images to be processed
path_in = "./samples"

# Output directory path where processed images will be saved
path_out = "./output"

# Maximum directory traversal depth
max_depth = 3

# List of target widths for resizing images
target_sizes = [1024, 2048, 4096]

# Number of threads to use for concurrent processing
threads = 4
